[package]
name = "nginx-keycloak"
description = "Keycloak Integration for Nginx via auth_request"
version = "0.1.0"
license = "MIT"
edition = "2021"
readme = "README.md"
repository = "https://github.com/Defelo/nginx-keycloak"

[[bin]]
name = "nginx-keycloak"
path = "src/main.rs"

[profile.release]
opt-level = 3
strip = "symbols"
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
color-eyre = { version = "0.6.2", default-features = false }
dotenv = { version = "0.15.0", default-features = false }
envy = { version = "0.4.2", default-features = false }
eyre = { version = "0.6.8", default-features = false }
log = { version = "0.4.17", default-features = false }
once_cell = { version = "1.15.0", default-features = false }
pretty_env_logger = { version = "0.4.0", default-features = false }
rand = { version = "0.8.5", default-features = false }
redis = { version = "0.21.6", default-features = false, features = ["aio", "tokio", "tokio-comp"] }
reqwest = { version = "0.11.12", default-features = false, features = ["json", "rustls-tls"] }
rocket = { version = "0.5.0-rc.2", default-features = false }
serde = { version = "1.0.145", default-features = false, features = ["derive"] }
url = { version = "2.3.1", default-features = false }
