[package]
name = "nginx-keycloak"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "nginx-keycloak"
path = "src/main.rs"

[profile.release]
opt-level = 3
strip = "symbols"

[dependencies]
dotenv = "0.15.0"
envy = "0.4.2"
log = "0.4.17"
once_cell = "1.14.0"
pretty_env_logger = "0.4.0"
rand = "0.8.5"
redis = { version = "0.21.6", features = ["aio", "tokio", "tokio-comp"] }
reqwest = { version = "0.11.11", features = ["json"] }
rocket = "0.5.0-rc.2"
serde = { version = "1.0.144", features = ["derive"] }
url = "2.3.1"
