[package]
name = "nginx-keycloak"
description = "Keycloak Integration for Nginx via auth_request"
version = "0.1.0"
license = "MIT"
edition = "2021"
readme = "README.md"
repository = "https://github.com/Defelo/nginx-keycloak"

[[bin]]
name = "nginx-keycloak"
path = "src/main.rs"

[profile.release]
opt-level = 3
strip = "symbols"
lto = true
codegen-units = 1
panic = "abort"

[dependencies]
color-eyre = "0.6.2"
dotenv = "0.15.0"
envy = "0.4.2"
eyre = "0.6.8"
log = "0.4.17"
once_cell = "1.15.0"
pretty_env_logger = "0.4.0"
rand = "0.8.5"
redis = { version = "0.21.6", features = ["aio", "tokio", "tokio-comp"] }
reqwest = { version = "0.11.12", features = ["json"] }
rocket = "0.5.0-rc.2"
serde = { version = "1.0.145", features = ["derive"] }
url = "2.3.1"
