version: '3.10'

services:
  nginx-keycloak:
    image: ghcr.io/defelo/nginx-keycloak
    build: .
    restart: always
    env_file: nginx-keycloak.env
    depends_on:
      - redis
    ports:
      - "127.0.0.1:8000:80"

  redis:
    image: redis:alpine
    restart: always
